import Layout from "@/components/layout/Layout"
import Category from "@/components/sections/Category"
import DealProduct1 from "@/components/sections/DealProduct1"
import Product1 from "@/components/sections/Product1"
import Shop from "@/components/sections/Shop"
import Slider1 from "@/components/sections/Slider1"
import { getPageBySlug } from "@/lib/payload-api"
export const metadata = {
  title: 'Ninico - Minimal NextJS React Template',
  description: 'Generated by create next app',
}

function getFirstBlock(layout, type) {
  if (!Array.isArray(layout)) return null
  return layout.find((b) => b && b.blockType === type) || null
}

function getRichTextValue(block) {
  if (!block) return null
  const value = block.content
  if (typeof value === 'string') return value
  // Lexical / structured richText (keep MVP: don't render yet)
  return null
}

export default async function Home() {
    let page = null
    try {
        page = await getPageBySlug('home')
    } catch {
        page = null
    }

    const layout = page?.doc?.layout || []
    const hero = getFirstBlock(layout, 'hero')
    const richText = getFirstBlock(layout, 'richText')
    const heroHeadline = hero?.headline
    const heroSubheadline = hero?.subheadline
    const richTextContent = getRichTextValue(richText)

    return (
        <>
            <Layout headerStyle={1} footerStyle={1}>
                {(page?.doc?.title || heroHeadline || richTextContent) ? (
                    <section className="pt-30 pb-10">
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-12">
                                    {page?.doc?.title ? <h2 className="mb-10">{page.doc.title}</h2> : null}
                                    {heroHeadline ? <h3 className="mb-10">{heroHeadline}</h3> : null}
                                    {heroSubheadline ? <p className="mb-10">{heroSubheadline}</p> : null}
                                    {richTextContent ? <p className="mb-0">{richTextContent}</p> : null}
                                </div>
                            </div>
                        </div>
                    </section>
                ) : null}
                <Slider1 />
                <Category />
                <Product1 />
                <DealProduct1 />
                <Shop />
            </Layout>
        </>
    )
}
